### ISSUE TITLE
I got an error when i use the rector rules for phpstan

### ISSUE THREAD

**Issue by WeedTest** [rectorphp/phpstan-rules#36]
Hello guys

i got this error when i put "- vendor/rector/phpstan-rules/config/config.neon" if phpstan.neon

![Capture d’écran du 2023-01-26 14-47-44](https://user-images.githubusercontent.com/71571547/214867096-f44bf18b-f324-4579-baf5-fb09e4214226.png)

**Comment by TomasVotruba** [comment]
Hi, you need to install https://packagist.org/packages/phpstan/extension-installer to enable service autoregistration

**Comment by WeedTest** [comment]
thanks
